### ISSUE TITLE
Container is built before Checkout step, so it doesn't know about the git repo

### ISSUE THREAD

**Issue by KevinGDialpad** [talkiq/confluence-wiki-sync#2]
While I was developing the Action I tested it by having the code in the same repo I was using it in, something like:
```
jobs:
  wiki-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Need 2 commits in order to be able to compare to the previous one

      - name: Wiki Sync
        uses: ./.github/actions/confluence-docs-sync
        with:
          wiki-base-url: https://example.org
          user: user@domain.tld
          token: ${{ secrets.TOKEN }}
          space-name: CoolSpace
          root-page-title: Root page
```
which is what I put in the README.

That was working:
![Screenshot from 2022-05-06 09-49-05](https://user-images.githubusercontent.com/46726602/167176930-b7b8c8a4-a889-45e3-9690-44105c3638a2.png)
Setup -> Checkout -> Wiki Sync -> Post Checkout -> Complete
All good.

When I released the action, I naively thought I could just replace `uses: ./.github/actions/confluence-docs-sync` with `uses: talkiq/confluence-docs-sync@v1.0.1` and things would work the same way, but no:

![Screenshot from 2022-05-04 17-26-56](https://user-images.githubusercontent.com/46726602/167177164-5d500426-5eab-4d30-8e6b-fa9d1b0e2de6.png)
Setup -> Build container -> Checkout -> Run container
So the container doesn't have the git repo.

Let's make this usable and update the README.
