### ISSUE TITLE
Add optional param for default branch

### ISSUE THREAD

**Issue by KevinGDialpad** [talkiq/confluence-wiki-sync#71]
We currently always use `f'https://github.com/{github_repo}/blob/HEAD/'` as the URL root, which result slightly awkward-looking URLs.

We could add an optional default-branch param and then have
```
  default-branch:
    description: ...
    required: false
    default: 'HEAD'
```
(need to keep HEAD as the default for backward compatibility)
```
    git_ref = os.environ['INPUT_DEFAULT-BRANCH']
    url_root_for_file = f'https://github.com/{github_repo}/blob/{git_ref}/'
```
